CREATE TABLE IF NOT EXISTS IPs
(
	id SERIAL NOT NULL PRIMARY KEY,
	address_first SMALLINT NOT NULL,
	address_second SMALLINT NOT NULL,
	address_third SMALLINT NOT NULL,
	address_fourth SMALLINT NOT NULL,
	port SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS Users
(
	id SERIAL NOT NULL PRIMARY KEY,
	name VARCHAR NOT NULL UNIQUE,
	clientStatus SMALLINT NOT NULL,
	ipAddress INTEGER REFERENCES IPs(id)
);